# docker-compose.yml - Linux Version (Multi-Architecture Optimized)

services:
  setup:
    image: alpine:latest
    container_name: ddc-linux-setup
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    command: >
      sh -c "
      echo 'Setting up Linux permissions...' &&
      chown -R 1000:1000 /app/config /app/logs &&
      chmod -R 755 /app/config /app/logs &&
      echo 'Linux setup completed!'
      "
    restart: "no"

  ddc:
    container_name: ddc-linux
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    restart: unless-stopped
    ports:
      - "8374:9374"
    volumes:
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_SOCKET=/var/run/docker.sock
      - DOCKER_CONTEXT=default
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
    networks:
      - ddc-linux-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9374/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    depends_on:
      - setup

networks:
  ddc-linux-network:
    driver: bridge
    name: ddc-linux-network
